### ISSUE TITLE
Strongly recommended to use a development-specific empty Obsidian Vault?

### ISSUE THREAD

**Issue by RobertChrist** [StinsonZhao/obsidian-plugin-goban-sgf#3]
Hey @StinsonZhao 

Pretty awesome to see that you put this together.  Well done and thank you!

Just a quick question from the readme before I start playing with this a bit.  What did this line refer to in the README?
"Strongly recommended to use a development-specific empty Obsidian Vault"

Was this a suggestion to do when actively developing on this repository?  Why?
Or is this something you are suggesting for anyone running this plugin?

**Comment by StinsonZhao** [comment]
@RobertChrist 

This advice is for developers who need to develop this plugin.

In fact, when developing any obsidian plugin, the developer should use a "development-specific empty Obsidian Vault". This is because we may mistakenly call some obsidian APIs during development and delete or alter some files by mistake, which can lead to data loss.
